# Generated by Django 4.2.16 on 2024-11-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mutual_support.user')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_help_offered', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual_support.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='mutual_support.profile')),
            ],
        ),
    ]
